id = "Àùyang"
name = "YANG Language Support"
version = "0.0.1"
schema_version = 1
authors = ["Sergei Proniakin <olitez27@gmail.com>"]
description = "This extension provides syntax highlighting and basic support for YANG language in Zed editor."
repository = "https://github.com/olitez/zed-yang"

[grammars.yang]
repository = "https://github.com/Hubro/tree-sitter-yang"
rev = "2c0e6be8dd4dcb961c345fa35c309ad4f5bd3502"
